function [] = plotTreeBH(plt_p, p)
%     % Tree structure with all 4 experiments.
%     parents_vec = [1 1 1 1,...
%         2 2 3 3 4 4 5 5 5 5 5,...
%         6 6 7 8 8 8 8 9 10 10 10 10 11,...
%         17 17 17 17 18];
%     node_names = [{'Thesis'},...
%         {'Experiment 4', 'Experiment 3', 'Experiment 2', 'Experiment 1'},...
%         {'Reach 4', 'Keyboard 4'},...
%         {'Exploratory 3', 'Confirmatory 3'},...
%         {'Exploratory 2', 'Confirmatory 2'},...
%         {'Reaction time 1', 'Movement time 1', 'COM 1', 'Traveled distance 1', 'Reach area 1'},...
%         {'Exploratory 4', 'Confirmatory 4'},...
%         {'RT 4'},...
%         {'Reaction time 3', 'Movement time 3', 'COM 3', 'Traveled distance 3'},...
%         {'Reach area 3'},...
%         {'Reaction time 2', 'Movement time 2', 'COM 2', 'Traveled distance 2'},...
%         {'Reach area 2'},...
%         {'Reaction time 4', 'Movement time 4', 'COM 4', 'Traveled distance 4'},...
%         {'Reach area 4'}];
% 
%     % Add p-values to tree.
%     exp1.react_p_val = load([p.PROC_DATA_FOLDER '/react_p_val_' p.DAY '_exp1.mat']);  exp1.react_p_val = exp1.react_p_val.p_val;
%     exp1.mt_p_val = load([p.PROC_DATA_FOLDER '/mt_p_val_' p.DAY '_exp1.mat']);  exp1.mt_p_val = exp1.mt_p_val.p_val;
%     exp1.com_p_val = load([p.PROC_DATA_FOLDER '/com_p_val_' p.DAY '_exp1.mat']);  exp1.com_p_val = exp1.com_p_val.p_val;
%     exp1.tot_dist_p_val = load([p.PROC_DATA_FOLDER '/tot_dist_p_val_' p.DAY '_exp1.mat']);  exp1.tot_dist_p_val = exp1.tot_dist_p_val.p_val;
%     exp1.ra_p_val = load([p.PROC_DATA_FOLDER '/ra_p_val_' p.DAY '_exp1.mat']);  exp1.ra_p_val = exp1.ra_p_val.p_val;
% 
%     exp4.keyboard_rt_p_val = load([p.PROC_DATA_FOLDER '/keyboard_rt_p_val_' p.DAY '_exp4_1.mat']);  exp4.keyboard_rt_p_val = exp4.keyboard_rt_p_val.p_val;
%     exp3.react_p_val = load([p.PROC_DATA_FOLDER '/react_p_val_' p.DAY '_exp3.mat']);  exp3.react_p_val = exp3.react_p_val.p_val;
%     exp3.mt_p_val = load([p.PROC_DATA_FOLDER '/mt_p_val_' p.DAY '_exp3.mat']);  exp3.mt_p_val = exp3.mt_p_val.p_val;
%     exp3.com_p_val = load([p.PROC_DATA_FOLDER '/com_p_val_' p.DAY '_exp3.mat']);  exp3.com_p_val = exp3.com_p_val.p_val;
%     exp3.tot_dist_p_val = load([p.PROC_DATA_FOLDER '/tot_dist_p_val_' p.DAY '_exp3.mat']);  exp3.tot_dist_p_val = exp3.tot_dist_p_val.p_val;
%     exp3.ra_p_val = load([p.PROC_DATA_FOLDER '/ra_p_val_' p.DAY '_exp3.mat']);  exp3.ra_p_val = exp3.ra_p_val.p_val;
%     
%     exp2.react_p_val = load([p.PROC_DATA_FOLDER '/react_p_val_' p.DAY '_exp2.mat']);  exp2.react_p_val = exp2.react_p_val.p_val;
%     exp2.mt_p_val = load([p.PROC_DATA_FOLDER '/mt_p_val_' p.DAY '_exp2.mat']);  exp2.mt_p_val = exp2.mt_p_val.p_val;
%     exp2.com_p_val = load([p.PROC_DATA_FOLDER '/com_p_val_' p.DAY '_exp2.mat']);  exp2.com_p_val = exp2.com_p_val.p_val;
%     exp2.tot_dist_p_val = load([p.PROC_DATA_FOLDER '/tot_dist_p_val_' p.DAY '_exp2.mat']);  exp2.tot_dist_p_val = exp2.tot_dist_p_val.p_val;
%     exp2.ra_p_val = load([p.PROC_DATA_FOLDER '/ra_p_val_' p.DAY '_exp2.mat']);  exp2.ra_p_val = exp2.ra_p_val.p_val;
% 
%     exp4.react_p_val = load([p.PROC_DATA_FOLDER '/react_p_val_' p.DAY '_exp4_1.mat']);  exp4.react_p_val = exp4.react_p_val.p_val;
%     exp4.mt_p_val = load([p.PROC_DATA_FOLDER '/mt_p_val_' p.DAY '_exp4_1.mat']);  exp4.mt_p_val = exp4.mt_p_val.p_val;
%     exp4.com_p_val = load([p.PROC_DATA_FOLDER '/com_p_val_' p.DAY '_exp4_1.mat']);  exp4.com_p_val = exp4.com_p_val.p_val;
%     exp4.tot_dist_p_val = load([p.PROC_DATA_FOLDER '/tot_dist_p_val_' p.DAY '_exp4_1.mat']);  exp4.tot_dist_p_val = exp4.tot_dist_p_val.p_val;
%     exp4.ra_p_val = load([p.PROC_DATA_FOLDER '/ra_p_val_' p.DAY '_exp4_1.mat']);  exp4.ra_p_val = exp4.ra_p_val.p_val;
% 
%     node_p_values = [nan,...
%         nan, nan, nan, nan,...
%         nan, nan,...
%         nan, nan,...
%         nan, nan,...
%         exp1.react_p_val, exp1.mt_p_val, exp1.com_p_val, exp1.tot_dist_p_val, exp1.ra_p_val,...
%         nan, nan,...
%         exp4.keyboard_rt_p_val,...
%         exp3.react_p_val, exp3.mt_p_val, exp3.com_p_val, exp3.tot_dist_p_val,...
%         exp3.ra_p_val,...
%         exp2.react_p_val, exp2.mt_p_val, exp2.com_p_val, exp2.tot_dist_p_val,...
%         exp2.ra_p_val,...
%         exp4.react_p_val, exp4.mt_p_val, exp4.com_p_val, exp4.tot_dist_p_val,...
%         exp4.ra_p_val];

    % Specify tree structure.
    parents_vec = [1 1,...
        2 2 3,...
        4 4 4 4 5];
    node_names = [{'Manuscript'},...
        {'Reaching', 'Keyboard'},...
        {'Exploratory', 'Confirmatory'},...
        {'RT'},...
        {'Reaction time', 'Movement time', 'COM', 'Traveled distance'},...
        {'Reach Area'}];

    % Add p-values to tree.
    exp4.keyboard_rt_p_val = load([p.PROC_DATA_FOLDER '/keyboard_rt_p_val_' p.DAY '_exp4_1.mat']);  exp4.keyboard_rt_p_val = exp4.keyboard_rt_p_val.p_val;
    exp4.react_p_val = load([p.PROC_DATA_FOLDER '/react_p_val_' p.DAY '_exp4_1.mat']);  exp4.react_p_val = exp4.react_p_val.p_val;
    exp4.mt_p_val = load([p.PROC_DATA_FOLDER '/mt_p_val_' p.DAY '_exp4_1.mat']);  exp4.mt_p_val = exp4.mt_p_val.p_val;
    exp4.com_p_val = load([p.PROC_DATA_FOLDER '/com_p_val_' p.DAY '_exp4_1.mat']);  exp4.com_p_val = exp4.com_p_val.p_val;
    exp4.tot_dist_p_val = load([p.PROC_DATA_FOLDER '/tot_dist_p_val_' p.DAY '_exp4_1.mat']);  exp4.tot_dist_p_val = exp4.tot_dist_p_val.p_val;
    exp4.ra_p_val = load([p.PROC_DATA_FOLDER '/ra_p_val_' p.DAY '_exp4_1.mat']);  exp4.ra_p_val = exp4.ra_p_val.p_val;

    node_p_values = [nan,...
        nan, nan, nan, nan,...
        exp4.keyboard_rt_p_val,...
        exp4.react_p_val, exp4.mt_p_val, exp4.com_p_val, exp4.tot_dist_p_val,...
        exp4.ra_p_val];

    % Create a a tree.
    g = createtree(parents_vec, node_names, node_p_values);
    
    % Run Tree-BH.
    plot_tree = 1; % plot it or not it.
    interactive_plot = 1;
    recalculate_p = 0;
    [g_output, g_plot_handle] = treeBH(g, plot_tree, interactive_plot, recalculate_p, plt_p.alpha_size);

    % Print results to terminal.
    disp('@@@@--------Tree-BH Correction--------@@@@')
    g_output.Nodes.name = string(g_output.Nodes.name);
    disp(g_output.Nodes(:, {'name','p','corr_p'}));
end